/**
 * This file will be generated by Typed Translator
 */
const translationBundle = new Map<string, Map<any, any>>();
translationBundle.set('pl', new Map());
let currentLang = translationBundle.get('pl');
currentLang!.set('month.1', 'styczeń');
currentLang!.set('month.2', 'luty');
currentLang!.set('month.3', 'marzec');
currentLang!.set('month.4', 'kwiecień');
currentLang!.set('month.5', 'maj');
currentLang!.set('month.6', 'czerwiec');
currentLang!.set('month.7', 'lipiec');
currentLang!.set('month.8', 'sierpień');
currentLang!.set('month.9', 'wrzesień');
currentLang!.set('month.10', 'październik');
currentLang!.set('month.11', 'listopad');
currentLang!.set('month.12', 'grudzień');
currentLang!.set('common.present', 'aktualnie');

currentLang!.set('common.skills', 'umiejętności');

currentLang!.set('common.contact', 'dane kontaktowe');
currentLang!.set('common.languages', 'języki');


currentLang!.set('education.title', 'wykształcenie');
currentLang!.set('education.mgr', 'Magister informatyki');
currentLang!.set('education.mgr.details', 'Politechnika Wrocławska');
currentLang!.set('education.engineer', 'Inżynier teleinformatyki');
currentLang!.set('education.engineer.details', 'Zachodniopomorski Uniwersytet Technologiczny');

currentLang!.set('experience.title', 'doświadczenie');
currentLang!.set('experience.unit4.title', 'Unit4');
currentLang!.set('experience.unit4.content', 'Jako Frontend developer: projekt w Angularze. Sporadycznie zadania w języku Java.');

currentLang!.set('experience.konsolamini.title', 'Konsolamini');
currentLang!.set('experience.konsolamini.content', 'W marcu 2019 założyłem działalność gospodarczą.');

currentLang!.set('experience.bv.title', 'blue veery');
currentLang!.set('experience.bv.content', 'Jako Full-stack developer: projekty pisane w Angular (4-8), React Native i Spring.');



export default translationBundle;
